
  name: vultr
  version: '1.13.0'
  summary: Vultr CLI and API client library, written in Go
  description: |
    Vultr CLI is a command line tool for using the Vultr API. It allows you to create and manage your virtual machines, SSH public keys, snapshots and startup scripts on your Vultr account. You can also use it to directly SSH into a Vultr virtual machine through the vultr ssh command.

  grade: stable
  confinement: devmode

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
